const plugin = require('tailwindcss/plugin')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'media', // config.useColorSchemeMediaQuery: true
  content: ['./src/**/*.{html,js,jsx,ts,tsx}'],
  theme: {
    screens: {
      sm: '32em',
      md: '48em',
      lg: '64em',
      xl: '96em',
      '2xl': '128em',
    },
    spacing: {
      0: '0px',
      1: '4px',
      2: '8px',
      3: '16px',
      4: '32px',
      5: '64px',
      6: '128px',
      7: '256px',
      8: '512px',
    },
    fontSize: {
      0: '12px',
      1: '16px',
      2: '20px',
      3: '24px',
      4: '32px',
      5: '48px',
      6: '64px',
      7: '96px',
      8: '128px',
      9: '160px',
      10: '192px',
    },
    fontFamily: {
      heading: [
        '"Phantom Sans"',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        'sans-serif',
      ],
      body: [
        '"Phantom Sans"',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        'sans-serif',
      ],
      mono: ['"SF Mono"', '"Roboto Mono"', 'Menlo', 'Consolas', 'monospace'],
    },
    fontWeight: {
      body: '400',
      bold: '700',
      heading: '700',
    },
    lineHeight: {
      limit: '0.875',
      title: '1',
      heading: '1.125',
      subheading: '1.25',
      caption: '1.375',
      body: '1.5',
    },
    letterSpacing: {
      title: '-0.009em',
      headline: '0.009em',
    },
    borderRadius: {
      none: '0px',
      small: '4px',
      DEFAULT: '8px',
      extra: '12px',
      ultra: '16px',
      circle: '9999px',
      full: '9999px',
    },
    boxShadow: {
      text: '0 1px 2px rgba(0, 0, 0, 0.25), 0 2px 4px rgba(0, 0, 0, 0.125)',
      small: '0 1px 2px rgba(0, 0, 0, 0.0625), 0 2px 4px rgba(0, 0, 0, 0.0625)',
      card: '0 4px 8px rgba(0, 0, 0, 0.125)',
      elevated: '0 1px 2px rgba(0, 0, 0, 0.0625), 0 8px 12px rgba(0, 0, 0, 0.125)',
      none: 'none',
    },
    maxWidth: {
      none: 'none',
      full: '100%',
      narrow: '512px',
      narrowPlus: '600px',
      copy: '680px',
      copyPlus: '768px',
      copyUltra: '980px',
      layout: '1024px',
      layoutPlus: '1200px',
      wide: '1536px',
      widePlus: '2048px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      inherit: 'inherit',
      darker: '#121217',
      dark: '#17171d',
      darkless: '#252429',
      black: '#1f2d3d',
      steel: '#273444',
      slate: '#3c4858',
      muted: '#8492a6',
      smoke: '#e0e6ed',
      snow: '#f9fafc',
      white: '#ffffff',
      red: '#ec3750',
      orange: '#ff8c37',
      yellow: '#f1c40f',
      green: '#33d6a6',
      cyan: '#5bc0de',
      blue: '#338eda',
      purple: '#a633d6',
      twitter: '#1da1f2',
      facebook: '#3b5998',
      instagram: '#e1306c',
      primary: '#ec3750',
      accent: '#338eda',
      secondary: '#3c4858',
      text: '#1f2d3d',
      'text-dark': '#ffffff',
      background: '#ffffff',
      'background-dark': '#17171d',
      elevated: '#ffffff',
      'elevated-dark': '#252429',
      sheet: '#f9fafc',
      'sheet-dark': '#252429',
      sunken: '#e0e6ed',
      'sunken-dark': '#121217',
      border: '#e0e6ed',
      'border-dark': '#252429',
      placeholder: '#8492a6',
      'placeholder-dark': '#3c4858',
      'muted-dark': '#8492a6',
      'secondary-dark': '#8492a6',
      'accent-dark': '#5bc0de',
    },
    extend: {},
  },
  plugins: [
    plugin(function ({ addComponents, addBase, theme }) {
      addBase({
        html: {
          fontFamily: theme('fontFamily.body'),
          lineHeight: theme('lineHeight.body'),
          fontWeight: theme('fontWeight.body'),
          color: theme('colors.text'),
          margin: '0',
          minHeight: '100vh',
          textRendering: 'optimizeLegibility',
          WebkitFontSmoothing: 'antialiased',
          MozOsxFontSmoothing: 'grayscale',
        },
        h1: {
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.heading'),
          marginTop: '0',
          marginBottom: '0',
          fontSize: theme('fontSize.5'),
        },
        h2: {
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.heading'),
          marginTop: '0',
          marginBottom: '0',
          fontSize: theme('fontSize.4'),
        },
        h3: {
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.heading'),
          marginTop: '0',
          marginBottom: '0',
          fontSize: theme('fontSize.3'),
        },
        h4: {
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.heading'),
          marginTop: '0',
          marginBottom: '0',
          fontSize: theme('fontSize.2'),
        },
        h5: {
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.heading'),
          marginTop: '0',
          marginBottom: '0',
          fontSize: theme('fontSize.1'),
        },
        h6: {
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.heading'),
          marginTop: '0',
          marginBottom: '0',
          fontSize: theme('fontSize.0'),
        },
        p: {
          color: theme('colors.text'),
          fontWeight: theme('fontWeight.body'),
          lineHeight: theme('lineHeight.body'),
          marginTop: theme('spacing.3'),
          marginBottom: theme('spacing.3'),
        },
        img: {
          maxWidth: '100%',
        },
        hr: {
          border: '0',
          borderBottom: '1px solid',
          borderColor: theme('colors.border'),
        },
        a: {
          color: theme('colors.primary'),
          textDecoration: 'underline',
          textUnderlinePosition: 'under',
          '&:focus, &:hover': {
            textDecorationStyle: 'wavy',
          },
        },
        pre: {
          fontFamily: theme('fontFamily.mono'),
          fontSize: theme('fontSize.1'),
          padding: theme('spacing.3'),
          color: theme('colors.text'),
          backgroundColor: theme('colors.sunken'),
          overflow: 'auto',
          borderRadius: theme('borderRadius.DEFAULT'),
          code: {
            color: 'inherit',
            marginLeft: '0',
            marginRight: '0',
            paddingLeft: '0',
            paddingRight: '0',
            '.comment, .prolog, .doctype, .cdata, .punctuation, .operator, .entity, .url': {
              color: theme('colors.muted'),
            },
            '.comment': {
              fontStyle: 'italic',
            },
            '.property, .tag, .boolean, .number, .constant, .symbol, .deleted, .function, .class-name, .regex, .important, .variable': {
              color: theme('colors.red'),
            },
            '.atrule, .attr-value, .keyword': {
              color: theme('colors.blue'),
            },
            '.selector, .attr-name, .string, .char, .builtin, .inserted': {
              color: theme('colors.orange'),
            },
          },
        },
        code: {
          fontFamily: theme('fontFamily.mono'),
          fontSize: 'inherit',
          color: theme('colors.purple'),
          backgroundColor: theme('colors.sunken'),
          borderRadius: theme('borderRadius.small'),
          marginLeft: theme('spacing.1'),
          marginRight: theme('spacing.1'),
          paddingLeft: theme('spacing.1'),
          paddingRight: theme('spacing.1'),
        },
        'p > code, li > code': {
          color: theme('colors.purple'),
          fontSize: '0.875em',
        },
        'p > a > code, li > a > code': {
          color: theme('colors.red'),
          fontSize: '0.875em',
        },
        li: {
          marginTop: theme('spacing.2'),
          marginBottom: theme('spacing.2'),
        },
        table: {
          width: '100%',
          marginTop: theme('spacing.4'),
          marginBottom: theme('spacing.4'),
          borderCollapse: 'separate',
          borderSpacing: 0,
          'th, td': {
            textAlign: 'left',
            paddingTop: '4px',
            paddingBottom: '4px',
            paddingRight: '4px',
            paddingLeft: '0',
            borderColor: theme('colors.border'),
            borderBottomStyle: 'solid',
          },
        },
        th: {
          verticalAlign: 'bottom',
          borderBottomWidth: '2px',
        },
        td: {
          verticalAlign: 'top',
          borderBottomWidth: '1px',
        },
      })
      addComponents({
        '.hc-text-heading': {
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.heading'),
          marginTop: '0',
          marginBottom: '0',
        },
        '.hc-text-title': {
          fontSize: theme('fontSize.4'),
          fontWeight: theme('fontWeight.bold'),
          letterSpacing: theme('letterSpacing.title'),
          lineHeight: theme('lineHeight.title'),
          '@screen sm': { fontSize: theme('fontSize.5') },
          '@screen md': { fontSize: theme('fontSize.6') },
        },
        '.hc-text-eyebrow': {
          color: theme('colors.muted'),
          fontSize: theme('fontSize.3'),
          fontWeight: theme('fontWeight.heading'),
          letterSpacing: theme('letterSpacing.headline'),
          lineHeight: theme('lineHeight.subheading'),
          textTransform: 'uppercase',
          marginTop: '0',
          marginBottom: theme('spacing.2'),
          '@screen sm': { fontSize: theme('fontSize.4') },
        },
        '.hc-text-caption': {
          color: theme('colors.muted'),
          fontWeight: '500',
          letterSpacing: theme('letterSpacing.headline'),
          lineHeight: theme('lineHeight.caption'),
        },
        '.hc-badge-pill': {
          borderRadius: theme('borderRadius.circle'),
          paddingLeft: theme('spacing.3'),
          paddingRight: theme('spacing.3'),
          paddingTop: theme('spacing.1'),
          paddingBottom: theme('spacing.1'),
          fontSize: theme('fontSize.1'),
        },
        '.hc-badge-outline': {
          borderRadius: theme('borderRadius.circle'),
          paddingLeft: theme('spacing.3'),
          paddingRight: theme('spacing.3'),
          paddingTop: theme('spacing.1'),
          paddingBottom: theme('spacing.1'),
          fontSize: theme('fontSize.1'),
          backgroundColor: 'transparent',
          border: '1px solid',
          borderColor: 'currentColor',
          fontWeight: theme('fontWeight.body'),
        },
        '.hc-btn-primary': {
          cursor: 'pointer',
          fontFamily: 'inherit',
          fontWeight: theme('fontWeight.bold'),
          borderRadius: theme('borderRadius.circle'),
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: theme('colors.primary'),
          color: theme('colors.white'),
          border: '0',
          boxShadow: theme('boxShadow.card'),
          letterSpacing: theme('letterSpacing.headline'),
          textDecoration: 'none',
          WebkitTapHighlightColor: 'transparent',
          transition: 'transform .125s ease-in-out, box-shadow .125s ease-in-out, background-color .125s ease-in-out',
          '&:focus, &:hover': {
            boxShadow: theme('boxShadow.elevated'),
            transform: 'scale(1.0625)',
          },
          '&:disabled': {
            cursor: 'not-allowed',
            opacity: '0.6',
            transform: 'none',
            boxShadow: theme('boxShadow.card'),
          },
          svg: {
            marginLeft: `-${theme('spacing.1')}`,
            marginRight: theme('spacing.2'),
          },
        },
        '.hc-btn-lg': {
          fontSize: theme('fontSize.3'),
          lineHeight: theme('lineHeight.title'),
          paddingLeft: theme('spacing.4'),
          paddingRight: theme('spacing.4'),
          paddingTop: theme('spacing.3'),
          paddingBottom: theme('spacing.3'),
        },
        '.hc-btn-outline': {
          backgroundColor: 'transparent',
          color: theme('colors.primary'),
          border: '2px solid currentColor',
        },
        '.hc-btn-outline-lg': {
          backgroundColor: 'transparent',
          color: theme('colors.primary'),
          border: '2px solid currentColor',
          lineHeight: theme('lineHeight.title'),
          fontSize: theme('fontSize.3'),
          paddingLeft: theme('spacing.4'),
          paddingRight: theme('spacing.4'),
          paddingTop: theme('spacing.3'),
          paddingBottom: theme('spacing.3'),
        },
        '.hc-btn-cta': {
          fontSize: theme('fontSize.2'),
        },
        '.hc-btn-cta-lg': {
          lineHeight: theme('lineHeight.title'),
          fontSize: theme('fontSize.3'),
          paddingLeft: theme('spacing.4'),
          paddingRight: theme('spacing.4'),
          paddingTop: theme('spacing.3'),
          paddingBottom: theme('spacing.3'),
        },
        '.hc-card-primary': {
          backgroundColor: theme('colors.elevated'),
          color: theme('colors.text'),
          padding: theme('spacing.3'),
          borderRadius: theme('borderRadius.extra'),
          boxShadow: theme('boxShadow.card'),
          overflow: 'hidden',
          '@screen sm': { padding: theme('spacing.4') },
        },
        '.hc-card-sunken': {
          backgroundColor: theme('colors.sunken'),
          padding: theme('spacing.3'),
          borderRadius: theme('borderRadius.extra'),
          '@screen sm': { padding: theme('spacing.4') },
        },
        '.hc-card-interactive': {
          textDecoration: 'none',
          WebkitTapHighlightColor: 'transparent',
          transition: 'transform .125s ease-in-out, box-shadow .125s ease-in-out',
          '&:hover, &:focus': {
            transform: 'scale(1.0625)',
            boxShadow: theme('boxShadow.elevated'),
          },
        },
        '.hc-card-translucent': {
          backgroundColor: 'rgba(255, 255, 255, 0.98)',
          color: theme('colors.text'),
          boxShadow: 'none',
          '@supports (-webkit-backdrop-filter: none) or (backdrop-filter: none)': {
            backgroundColor: 'rgba(255, 255, 255, 0.75)',
            backdropFilter: 'saturate(180%) blur(20px)',
            WebkitBackdropFilter: 'saturate(180%) blur(20px)',
          },
          '@media (prefers-reduced-transparency: reduce)': {
            backdropFilter: 'none',
            WebkitBackdropFilter: 'none',
          },
        },
        '.hc-card-translucent-dark': {
          backgroundColor: 'rgba(0, 0, 0, 0.875)',
          color: theme('colors.white'),
          boxShadow: 'none',
          '@supports (-webkit-backdrop-filter: none) or (backdrop-filter: none)': {
            backgroundColor: 'rgba(0, 0, 0, 0.625)',
            backdropFilter: 'saturate(180%) blur(16px)',
            WebkitBackdropFilter: 'saturate(180%) blur(16px)',
          },
          '@media (prefers-reduced-transparency: reduce)': {
            backdropFilter: 'none',
            WebkitBackdropFilter: 'none',
          },
        },
        '.hc-alert-primary': {
          borderRadius: theme('borderRadius.DEFAULT'),
          backgroundColor: theme('colors.orange'),
          color: theme('colors.background'),
          fontWeight: theme('fontWeight.body'),
        },
        '.hc-input': {
          backgroundColor: theme('colors.elevated'),
          color: theme('colors.text'),
          fontFamily: 'inherit',
          borderRadius: theme('borderRadius.DEFAULT'),
          border: '0',
          '&::placeholder': {
            color: theme('colors.placeholder'),
          },
          '&[type="search"]::-webkit-search-decoration': {
            display: 'none',
          },
        },
        '.hc-label': {
          color: theme('colors.text'),
          display: 'flex',
          flexDirection: 'column',
          textAlign: 'left',
          lineHeight: theme('lineHeight.caption'),
          fontSize: theme('fontSize.2'),
        },
        '.hc-label-horiz': {
          color: theme('colors.text'),
          display: 'flex',
          alignItems: 'center',
          textAlign: 'left',
          lineHeight: theme('lineHeight.caption'),
          fontSize: theme('fontSize.2'),
          svg: {
            color: theme('colors.muted'),
          },
        },
        '.hc-slider': {
          color: theme('colors.primary'),
        },
        '.hc-visually-hidden': {
          position: 'absolute',
          height: '1px',
          width: '1px',
          overflow: 'hidden',
          clip: 'rect(1px, 1px, 1px, 1px)',
          whiteSpace: 'nowrap',
        },
        '.hc-container': {
          maxWidth: theme('maxWidth.layout'),
          width: '100%',
          marginLeft: 'auto',
          marginRight: 'auto',
          paddingLeft: theme('spacing.3'),
          paddingRight: theme('spacing.3'),
          '@screen md': {
            maxWidth: theme('maxWidth.layoutPlus'),
          },
        },
        '.hc-container-wide': {
          maxWidth: theme('maxWidth.layout'),
          width: '100%',
          marginLeft: 'auto',
          marginRight: 'auto',
          paddingLeft: theme('spacing.3'),
          paddingRight: theme('spacing.3'),
          '@screen md': {
            maxWidth: theme('maxWidth.wide'),
          },
        },
        '.hc-container-copy': {
          maxWidth: theme('maxWidth.copy'),
          width: '100%',
          marginLeft: 'auto',
          marginRight: 'auto',
          paddingLeft: theme('spacing.3'),
          paddingRight: theme('spacing.3'),
          '@screen md': {
            maxWidth: theme('maxWidth.copyPlus'),
          },
        },
        '.hc-container-narrow': {
          maxWidth: theme('maxWidth.narrow'),
          width: '100%',
          marginLeft: 'auto',
          marginRight: 'auto',
          paddingLeft: theme('spacing.3'),
          paddingRight: theme('spacing.3'),
          '@screen md': {
            maxWidth: theme('maxWidth.narrowPlus'),
          },
        },
      })
    }),
  ],
}