/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flavortown API
 *
 * You need an API key to use this! Go to your account settings.
 * OpenAPI spec version: v1
 */

import { Type } from "@sinclair/typebox";
import { Nullish } from "../typeUtils";

export namespace FTTypes {
  /**
   * Fetch a list of projects. Ratelimit: 5 reqs/min, 20 reqs/min if searching.
   * @summary List projects
   */
  export const listProjectsQueryLimitMax = 100;

  export const ListProjectsQueryParams = Type.Object({
    page: Nullish(
      Type.Number({
        description: "Page number for pagination",
      }),
    ),
    limit: Nullish(
      Type.Number({
        maximum: listProjectsQueryLimitMax,
        description: "Number of results per page (max 100)",
      }),
    ),
    query: Nullish(
      Type.String({
        description: "Search projects by title or description",
      }),
    ),
  }, {
    description: "ListProjectsQueryParams",
  });

  export const ListProjectsResponse = Type.Object({
    projects: Nullish(
      Type.Array(
        Type.Object({
          id: Nullish(Type.Number()),
          title: Nullish(Type.String()),
          description: Nullish(Type.String()),
          repo_url: Nullish(Type.String()),
          demo_url: Nullish(Type.String()),
          readme_url: Nullish(Type.String()),
          ai_declaration: Nullish(Type.String()),
          ship_status: Nullish(Type.String()),
          devlog_ids: Nullish(Type.Array(Type.Number())),
          banner_url: Nullish(Type.String()),
          created_at: Nullish(Type.String({ format: "date-time" })),
          updated_at: Nullish(Type.String({ format: "date-time" })),
        }),
      ),
    ),
    pagination: Nullish(
      Type.Object({
        current_page: Nullish(Type.Number()),
        total_pages: Nullish(Type.Number()),
        total_count: Nullish(Type.Number()),
        next_page: Nullish(Type.Number()),
      }),
    ),
  }, {
    description: "ListProjectsResponse",
  });

  /**
   * Fetch a specific project by ID. Ratelimit: 30 reqs/min.
   * @summary Get a project
   */
  export const GetProjectParams = Type.Object({
    id: Type.Number(),
  }, {
    description: "GetProjectParams",
  });

  export const GetProjectResponse = Type.Object({
    id: Nullish(Type.Number()),
    title: Nullish(Type.String()),
    description: Nullish(Type.String()),
    repo_url: Nullish(Type.String()),
    demo_url: Nullish(Type.String()),
    readme_url: Nullish(Type.String()),
    ai_declaration: Nullish(Type.String()),
    ship_status: Nullish(Type.String()),
    devlog_ids: Nullish(Type.Array(Type.Number())),
    banner_url: Nullish(Type.String()),
    created_at: Nullish(Type.String({ format: "date-time" })),
    updated_at: Nullish(Type.String({ format: "date-time" })),
  }, {
    description: "GetProjectResponse",
  });

  /**
   * Update an existing project.
   * @summary Update a project
   */
  export const UpdateProjectParams = Type.Object({
    id: Type.Number(),
  }, {
    description: "UpdateProjectParams",
  });

  export const UpdateProjectResponse = Type.Object({
    id: Nullish(Type.Number()),
    title: Nullish(Type.String()),
    description: Nullish(Type.String()),
    repo_url: Nullish(Type.String()),
    demo_url: Nullish(Type.String()),
    readme_url: Nullish(Type.String()),
    ai_declaration: Nullish(Type.String()),
    ship_status: Nullish(Type.String()),
    devlog_ids: Nullish(Type.Array(Type.Number())),
    banner_url: Nullish(Type.String()),
    created_at: Nullish(Type.String({ format: "date-time" })),
    updated_at: Nullish(Type.String({ format: "date-time" })),
  }, {
    description: "UpdateProjectResponse",
  });

  /**
   * Fetch all devlogs for a specific project.
   * @summary List project devlogs
   */
  export const ListProjectDevlogsParams = Type.Object({
    project_id: Type.Number(),
  }, {
    description: "ListProjectDevlogsParams",
  });

  export const listProjectDevlogsQueryLimitMax = 100;

  export const ListProjectDevlogsQueryParams = Type.Object({
    page: Nullish(
      Type.Number({
        description: "Page number for pagination",
      }),
    ),
    limit: Nullish(
      Type.Number({
        maximum: listProjectDevlogsQueryLimitMax,
        description: "Number of results per page (max 100)",
      }),
    ),
  }, {
    description: "ListProjectDevlogsQueryParams",
  });

  export const ListProjectDevlogsResponse = Type.Object({
    devlogs: Nullish(
      Type.Array(
        Type.Object({
          id: Nullish(Type.Number()),
          body: Nullish(Type.String()),
          comments_count: Nullish(Type.Number()),
          duration_seconds: Nullish(Type.Number()),
          likes_count: Nullish(Type.Number()),
          scrapbook_url: Nullish(Type.String()),
          created_at: Nullish(Type.String({ format: "date-time" })),
          updated_at: Nullish(Type.String({ format: "date-time" })),
          media: Nullish(
            Type.Array(
              Type.Object({
                url: Nullish(Type.String()),
                content_type: Nullish(Type.String()),
              }),
            ),
          ),
          comments: Nullish(
            Type.Array(
              Type.Object({
                id: Nullish(Type.Number()),
                author: Nullish(
                  Type.Object({
                    id: Nullish(Type.Number()),
                    display_name: Nullish(Type.String()),
                    avatar: Nullish(Type.String()),
                  }),
                ),
                body: Nullish(Type.String()),
                created_at: Nullish(Type.String({ format: "date-time" })),
                updated_at: Nullish(Type.String({ format: "date-time" })),
              }),
            ),
          ),
        }),
      ),
    ),
    pagination: Nullish(
      Type.Object({
        current_page: Nullish(Type.Number()),
        total_pages: Nullish(Type.Number()),
        total_count: Nullish(Type.Number()),
        next_page: Nullish(Type.Number()),
      }),
    ),
  }, {
    description: "ListProjectDevlogsResponse",
  });

  /**
   * Fetch all devlogs across all projects.
   * @summary List devlogs
   */
  export const listDevlogsQueryLimitMax = 100;

  export const ListDevlogsQueryParams = Type.Object({
    page: Nullish(
      Type.Number({
        description: "Page number for pagination",
      }),
    ),
    limit: Nullish(
      Type.Number({
        maximum: listDevlogsQueryLimitMax,
        description: "Number of results per page (max 100)",
      }),
    ),
  }, {
    description: "ListDevlogsQueryParams",
  });

  export const ListDevlogsResponse = Type.Object({
    devlogs: Nullish(
      Type.Array(
        Type.Object({
          id: Nullish(Type.Number()),
          body: Nullish(Type.String()),
          comments_count: Nullish(Type.Number()),
          duration_seconds: Nullish(Type.Number()),
          likes_count: Nullish(Type.Number()),
          scrapbook_url: Nullish(Type.String()),
          created_at: Nullish(Type.String({ format: "date-time" })),
          updated_at: Nullish(Type.String({ format: "date-time" })),
          media: Nullish(
            Type.Array(
              Type.Object({
                url: Nullish(Type.String()),
                content_type: Nullish(Type.String()),
              }),
            ),
          ),
          comments: Nullish(
            Type.Array(
              Type.Object({
                id: Nullish(Type.Number()),
                author: Nullish(
                  Type.Object({
                    id: Nullish(Type.Number()),
                    display_name: Nullish(Type.String()),
                    avatar: Nullish(Type.String()),
                  }),
                ),
                body: Nullish(Type.String()),
                created_at: Nullish(Type.String({ format: "date-time" })),
                updated_at: Nullish(Type.String({ format: "date-time" })),
              }),
            ),
          ),
        }),
      ),
    ),
    pagination: Nullish(
      Type.Object({
        current_page: Nullish(Type.Number()),
        total_pages: Nullish(Type.Number()),
        total_count: Nullish(Type.Number()),
        next_page: Nullish(Type.Number()),
      }),
    ),
  }, {
    description: "ListDevlogsResponse",
  });

  /**
   * Fetch a devlog by ID.
   * @summary Get a devlog
   */
  export const GetDevlogParams = Type.Object({
    id: Type.Number(),
  }, {
    description: "GetDevlogParams",
  });

  export const GetDevlogResponse = Type.Object({
    id: Nullish(Type.Number()),
    body: Nullish(Type.String()),
    comments_count: Nullish(Type.Number()),
    duration_seconds: Nullish(Type.Number()),
    likes_count: Nullish(Type.Number()),
    scrapbook_url: Nullish(Type.String()),
    created_at: Nullish(Type.String({ format: "date-time" })),
    updated_at: Nullish(Type.String({ format: "date-time" })),
    media: Nullish(
      Type.Array(
        Type.Object({
          url: Nullish(Type.String()),
          content_type: Nullish(Type.String()),
        }),
      ),
    ),
    comments: Nullish(
      Type.Array(
        Type.Object({
          id: Nullish(Type.Number()),
          author: Nullish(
            Type.Object({
              id: Nullish(Type.Number()),
              display_name: Nullish(Type.String()),
              avatar: Nullish(Type.String()),
            }),
          ),
          body: Nullish(Type.String()),
          created_at: Nullish(Type.String({ format: "date-time" })),
          updated_at: Nullish(Type.String({ format: "date-time" })),
        }),
      ),
    ),
  }, {
    description: "GetDevlogResponse",
  });

  /**
   * Fetch a list of store items. Ratelimit: 5 reqs/min.
   * @summary List store items
   */
  export const ListStoreItemsResponseItem = Type.Object({
    id: Nullish(Type.Number()),
    name: Nullish(Type.String()),
    description: Nullish(Type.String()),
    old_prices: Nullish(Type.Array(Type.Unknown())),
    limited: Nullish(Type.Boolean()),
    stock: Nullish(Type.Number()),
    type: Nullish(Type.String()),
    show_in_carousel: Nullish(Type.Boolean()),
    accessory_tag: Nullish(Type.String()),
    agh_contents: Nullish(
      Type.Union([
        Type.String(),
        Type.Array(Type.Unknown()),
        Type.Record(Type.String(), Type.Unknown()),
      ]),
    ),
    attached_shop_item_ids: Nullish(Type.Array(Type.Unknown())),
    buyable_by_self: Nullish(Type.Boolean()),
    long_description: Nullish(Type.String()),
    max_qty: Nullish(Type.Number()),
    one_per_person_ever: Nullish(Type.Boolean()),
    sale_percentage: Nullish(Type.Number()),
    image_url: Nullish(Type.String()),
    enabled: Nullish(
      Type.Object({
        enabled_au: Nullish(Type.Boolean()),
        enabled_ca: Nullish(Type.Boolean()),
        enabled_eu: Nullish(Type.Boolean()),
        enabled_in: Nullish(Type.Boolean()),
        enabled_uk: Nullish(Type.Boolean()),
        enabled_us: Nullish(Type.Boolean()),
        enabled_xx: Nullish(Type.Boolean()),
      }),
    ),
    ticket_cost: Nullish(
      Type.Object({
        base_cost: Nullish(Type.Number()),
        au: Nullish(Type.Number()),
        ca: Nullish(Type.Number()),
        eu: Nullish(Type.Number()),
        in: Nullish(Type.Number()),
        uk: Nullish(Type.Number()),
        us: Nullish(Type.Number()),
        xx: Nullish(Type.Number()),
      }),
    ),
  }, {
    description: "ListStoreItemsResponseItem",
  });

  export const ListStoreItemsResponse = Type.Array(
    ListStoreItemsResponseItem,
    {
      description: "ListStoreItemsResponse",
    },
  );

  /**
   * Fetch a specific store item by ID. Ratelimit: 30 reqs/min.
   * @summary Get a store item
   */
  export const GetStoreItemParams = Type.Object({
    id: Type.Number(),
  }, {
    description: "GetStoreItemParams",
  });

  export const GetStoreItemResponse = Type.Object({
    id: Nullish(Type.Number()),
    name: Nullish(Type.String()),
    description: Nullish(Type.String()),
    old_prices: Nullish(Type.Array(Type.Unknown())),
    limited: Nullish(Type.Boolean()),
    stock: Nullish(Type.Number()),
    type: Nullish(Type.String()),
    show_in_carousel: Nullish(Type.Boolean()),
    accessory_tag: Nullish(Type.String()),
    agh_contents: Nullish(
      Type.Union([
        Type.String(),
        Type.Array(Type.Unknown()),
        Type.Record(Type.String(), Type.Unknown()),
      ]),
    ),
    attached_shop_item_ids: Nullish(Type.Array(Type.Unknown())),
    buyable_by_self: Nullish(Type.Boolean()),
    long_description: Nullish(Type.String()),
    max_qty: Nullish(Type.Number()),
    one_per_person_ever: Nullish(Type.Boolean()),
    sale_percentage: Nullish(Type.Number()),
    image_url: Nullish(Type.String()),
    enabled: Nullish(
      Type.Object({
        enabled_au: Nullish(Type.Boolean()),
        enabled_ca: Nullish(Type.Boolean()),
        enabled_eu: Nullish(Type.Boolean()),
        enabled_in: Nullish(Type.Boolean()),
        enabled_uk: Nullish(Type.Boolean()),
        enabled_us: Nullish(Type.Boolean()),
        enabled_xx: Nullish(Type.Boolean()),
      }),
    ),
    ticket_cost: Nullish(
      Type.Object({
        base_cost: Nullish(Type.Number()),
        au: Nullish(Type.Number()),
        ca: Nullish(Type.Number()),
        eu: Nullish(Type.Number()),
        in: Nullish(Type.Number()),
        uk: Nullish(Type.Number()),
        us: Nullish(Type.Number()),
        xx: Nullish(Type.Number()),
      }),
    ),
  }, {
    description: "GetStoreItemResponse",
  });

  /**
   * Fetch a list of users. Ratelimit: 5 reqs/min.
   * @summary List users
   */
  export const listUsersQueryLimitMax = 100;

  export const ListUsersQueryParams = Type.Object({
    page: Nullish(
      Type.Number({
        description: "Page number for pagination",
      }),
    ),
    limit: Nullish(
      Type.Number({
        maximum: listUsersQueryLimitMax,
        description: "Number of results per page (max 100)",
      }),
    ),
    query: Nullish(
      Type.String({
        description: "Search users by display name or slack ID",
      }),
    ),
  }, {
    description: "ListUsersQueryParams",
  });

  export const ListUsersResponse = Type.Object({
    users: Nullish(
      Type.Array(
        Type.Object({
          id: Nullish(Type.Number()),
          slack_id: Nullish(Type.String()),
          display_name: Nullish(Type.String()),
          avatar: Nullish(Type.String()),
          project_ids: Nullish(Type.Array(Type.Number())),
          cookies: Nullish(Type.Number()),
        }),
      ),
    ),
    pagination: Nullish(
      Type.Object({
        current_page: Nullish(Type.Number()),
        total_pages: Nullish(Type.Number()),
        total_count: Nullish(Type.Number()),
        next_page: Nullish(Type.Number()),
      }),
    ),
  }, {
    description: "ListUsersResponse",
  });

  /**
   * Fetch a specific user by ID. Use "me" as the ID to fetch the authenticated user.
   * @summary Get a user
   */
  export const GetUserParams = Type.Object({
    id: Type.String({
      description: 'User ID or "me" for the authenticated user',
    }),
  }, {
    description: "GetUserParams",
  });

  export const GetUserResponse = Type.Intersect([
    Type.Object({
      id: Nullish(Type.Number()),
      slack_id: Nullish(Type.String()),
      display_name: Nullish(Type.String()),
      avatar: Nullish(Type.String()),
      project_ids: Nullish(Type.Array(Type.Number())),
      cookies: Nullish(Type.Number()),
    }),
    Type.Object({
      vote_count: Nullish(Type.Number()),
      like_count: Nullish(Type.Number()),
      devlog_seconds_total: Nullish(Type.Number()),
      devlog_seconds_today: Nullish(Type.Number()),
      achievements: Nullish(
        Type.Array(
          Type.Object({
            slug: Nullish(Type.String()),
            name: Nullish(Type.String()),
            description: Nullish(Type.String()),
          }),
        ),
      ),
    }),
  ], {
    description: "GetUserResponse",
  });

  /**
   * Fetch a paginated list of projects belonging to a specific user.
   * Use "me" as the user ID to fetch projects for the authenticated user.
   * @summary List projects for a user
   */
  export const ListUserProjectsParams = Type.Object({
    id: Type.String({
      description: 'User ID or "me" for the authenticated user',
    }),
  })
  export const ListUserProjectsQueryParams = Type.Object({
    page: Nullish(
      Type.Number({
        description: "Page number for pagination",
      }),
    ),
    limit: Nullish(
      Type.Number({
        maximum: 100,
        description: "Number of results per page (max 100)",
      }),
    ),
  }, {
    description: "ListUserProjectsQueryParams",
  });

  export const ListUserProjectsResponse = Type.Object({
    projects: Type.Array(
      Type.Object({
        id: Type.Number(),
        title: Type.String(),
        description: Type.String(),
        repo_url: Type.String(),
        demo_url: Type.String(),
        readme_url: Type.String(),
        ai_declaration: Nullish(Type.String()),
        ship_status: Type.String(),
        devlog_ids: Type.Array(Type.Number()),
        banner_url: Nullish(Type.String()),
        created_at: Type.String(),
        updated_at: Type.String(),
      }),
    ),
    pagination: Nullish(
      Type.Object({
        current_page: Nullish(Type.Number()),
        total_pages: Nullish(Type.Number()),
        total_count: Nullish(Type.Number()),
        next_page: Nullish(Type.Number()),
      }),
    ),
  }, {
    description: "ListUserProjectsResponse",
  });
}